# Generated by Django 6.0.5 on 2026-06-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporttype',
            old_name='title',
            new_name='name',
        ),
    ]
